export default {
    ADD_FAVORITE_MOVIE: 'ADD_FAVORITE_MOVIE',
    REMOVE_FAVORITE_MOVIE: 'REMOVE_FAVORITE_MOVIE',
    SET_MOVIES: 'SET_MOVIES',
    SET_ERROR: 'SET_ERROR',
    LOAD_ALL_ARTICLES: 'LOAD_ALL_ARTICLES',
    SET_ALL_ARTICLES: 'SET_ALL_ARTICLES',
    REMOVE_ARTICLE: 'REMOVE_ARTICLE'
};